### ISSUE TITLE
Bug in volume counter

### ISSUE THREAD

**Issue by nerdosity** [nicolaus-hee/esp8266-benq-rs232-mqtt#1]
```
void benq_set_volume(int target_volume) {
...
  for(int i = 0; i <= abs(delta); i++) {
...
}
```

should be:

```
void benq_set_volume(int target_volume) {
...
  for(int i = 1; i <= abs(delta); i++) {
...
}
```
Otherwise volume will go crazy with automation in Home Assistant, and it alway switch to 0 to 2 etc...

**Comment by nicolaus-hee** [comment]
Thanks. Are you sure this is related to Home Assistant? if `i = 1` then the loop has one too few iterations. Asking to go from 2 to 4 will only go to 3, going from 2 to 3 will fail altogether. Is it possible you experienced this behavior when toggling several volume changes at once? During my testing, I found that the BenQ easily confuses when several volume commands are sent at once -- and unfortunately, their protocol won't let you supply a target volume but you must toggle in steps of +1 or -1...
