### ISSUE TITLE
Response is read from wrong Serial interface

### ISSUE THREAD

**Issue by FelixvanBeusekom** [nicolaus-hee/esp8266-benq-rs232-mqtt#2]
Commands to the projector are written using **Serial1**. However, the response is captured using **Serial**. I found this issue and it solved a problem for me.

https://github.com/nicolaus-hee/esp8266-benq-rs232-mqtt/blob/8d65c34689ab81cc9010ed1e955b9649e82669f9/esp8266-benq-rs232-mqtt.ino#L157

**Comment by heizij** [comment]
how to distinguish HDMI1 and HDMI2？
