### ISSUE TITLE
Home Assistant Integration?

### ISSUE THREAD

**Issue by Jinsin456** [nicolaus-hee/esp8266-benq-rs232-mqtt#4]
This may be a stupid question so I apologize if it is.

Because this publishes MQTT messages, would that mean they could be picked up and used by Mosquito in Home Assistant?

Thank you

**Comment by nicolaus-hee** [comment]
Yes, correct. Suggest you look for a MQTT tutorial for Home Assistant to set it up. Good luck.

**Comment by Jinsin456** [comment]
Thank you, I use MQTT in HA for a least 1 thing IIRC but wasn't sure how universal it was. Blindy set it up and it worked so don't really know the workings of I'm honest 🤣🤣

**Comment by nicolaus-hee** [comment]
Resolved
